name: Build .NET API

on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean duplicate directories
        run: |
          echo "Removing duplicate FFmpeg.API directory (empty one)"
          rm -rf FFmpeg.API
          echo "Directory contents after cleanup:"
          ls -la

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore
